### ISSUE TITLE
Crashing when the sample rate is to high.

### ISSUE THREAD

**Issue by PaulmagCookies** [StratusFearMe21/listenbrainz-poweramp#1]
The app crashes with the error code: Error in poweramp listenbrainz panic on thread '<unnamed>' panicked at 'unsupoported format: IoError(Custom {kind: UnexpectedEof, error: "end of stream"})': src/lib.rs:553

I tried to find out when this happens. I found out that it happens with songs in my libary that have a sample rate of 192 kHz. 96 kHz are fine. I dont have any in between so I dont know at which sample rate it happens exactly. They all have a high bitrate too between 5500 kbit/s 6800 kbit/s. All songs have a bit depth of 24 bit. 

I could just resample these songs but maybe this can be fixed.

**Comment by StratusFearMe21** [comment]
Interesting. 192KHz works for me
![Screenshot_20241024_132725_Poweramp.png](https://github.com/user-attachments/assets/ea601161-6f5f-43d6-8df6-972c17d2b636)

Could you send in a screenshot like the one above for the files that are causing issues

**Comment by PaulmagCookies** [comment]
![Screenshot_20241024-215200](https://github.com/user-attachments/assets/d754bf88-8e47-4b38-90e5-96819dddd240)

**Comment by StratusFearMe21** [comment]
Hmmmmm. I can't really reproduce this unless you send me the FLAC file itself. My suspicion is that it's not the sample rate, but the tags on that file. Maybe resampling the file re-writes the tags on it in a compatible way. Is there some way you can send me that FLAC file?

**Comment by StratusFearMe21** [comment]
One other thing I would try is re-encoding the FLAC file. Just run it through the `flac` tool or `ffmpeg` and see if it fixes up the file for you

```sh
flac -8 input.flac output.flac
```
The flac tool: https://xiph.org/flac/download.html

Or

```sh
ffmpeg -i input.flac -map_metadata 0 -c:a flac -compression-level 8 output.flac
```
ffmpeg: https://ffmpeg.org//download.html

**Comment by StratusFearMe21** [comment]
The flac tool: https://xiph.org/flac/download.html

**Comment by PaulmagCookies** [comment]
https://mega.nz/file/RKJACYKa#gyTRvZokCyElc7NCF3YAdbfLojOGQhdiuN3JfsEzvmQ
I uploaded the flac to my mega account. I am in a rush so I couldnt re-encode it now. Need to do this after I'm back home.

**Comment by StratusFearMe21** [comment]
Yep! I was able to reproduce the issue you were experiencing, and re-encoding the flac file seems to solve it

```sh
flac -8 05\ Clocks.flac -o 05\ Clocks_fixed.flac
```

![Screenshot_20241025_004436_Mull.png](https://github.com/user-attachments/assets/4210f532-8d32-4878-8e7f-f7bc087db422)

![Screenshot_20241025_004553_Chrome.png](https://github.com/user-attachments/assets/1866200c-5adb-451a-836d-0fe41573d8bc)

**Comment by PaulmagCookies** [comment]
But do you know why this happens and I first need to reencode? 

And I have multiple Files that are 192 kHz.
Can I re-encode all files from a given folder to another given folder via ffmpeg or flac?

**Comment by PaulmagCookies** [comment]
I did re-encode them now and it works, but I still wonder why I first need to re-encode them.

Thanks for the help tho.

**Comment by StratusFearMe21** [comment]
The library this app uses to read tags (symphonia), doesn't seem to be error tolerant. I should probably update the version of that library in use anyway
